### PR TITLE
Add Position and Len for flac

### PR DESCRIPTION
**Pull request by cswank**
d.stream.Info.NSamples is uint64 so calling
int() on it could result in an overflow.  I
have no idea how likely that is, but if it happens
then Position() will return -1.

I also don't know if this PR is the intent behind the beep.StreamSeeker interface, but it's working great for the app that I built using beep.

### CODE REVIEW

**Comment by faiface** [comment]
Cool, thanks! @mewmew, can you confirm this is correct?

**Comment by cswank** [comment]
I think it might not be 100% correct.  The songs I've been playing never get to Len().  Position() seems to stop short each time.

**Comment by cswank** [comment]
I think I fixed it with the 2nd commit: update d.pos on EOF error.

**Comment by mewmew** [comment]
> Cool, thanks! @mewmew, can you confirm this is correct?

Looks correct from what I can tell. Good job @cswank :) Now there is only one method left to implement! Seek.

**Comment by cswank** [comment]
My app would benefit from Seek.  I'll take a look and see how brave I feel after some reading.

**Comment by mewmew** [comment]
> My app would benefit from Seek. I'll take a look and see how brave I feel after some reading.

That's great to hear! Preemptively, I've started writing a hymn that will be sung around campfires for generations to come. ♩♪♬♩

**Comment by cswank** [comment]
Hey @faiface, this is a friendly reminder that this PR should be good to go.

**Comment by faiface** [comment]
Oh, sorry, I forgot :) Here we go

**Pull request merged**
