### PR TITLE
Parametric equalizer

### PR DESCRIPTION
**Pull request by cswank**
based on https://octovoid.com/2017/11/04/coding-a-parametric-equalizer-for-audio-applications/

### CODE REVIEW

**Comment by cswank** [comment]
I think I copied the c++ code correctly to Go, however,

**Comment by faiface** [comment]
This looks cool! @dusk125 will do a proper review, here's just a quick note from me: I see you're returning an `*Equalizer` struct who's only methods are the ones of the `Streamer` interface. In such cases, I think it's better to make the `Equalizer` struct unexported and simply return an opaque `Streamer` value.

**Comment by cswank** [comment]
@faiface sounds good, I made those changes.

**Comment by faiface** [comment]
One more note: I see you use `fs float64` to denote the sample frequency. The rest of Beep uses `beep.SampleRate`, so I think it would be better to use it here as well.

**Comment by cswank** [comment]
@faiface and @dusk125 I just pushed that change.   Also, I have one more commit ready implements an (optional) stereo equalizer.  Would you rather take a look at the code as is now before I push the stereo change?  Stereo makes the code a good deal more complicated so maybe it would be good to verify the functionality in mono first.

**Comment by cswank** [comment]
Never mind, I'm going to push the stereo change because I'm about to be driving for 2 days.

**Comment by dusk125** [comment]
Sounds good! That'll give me some time to review and wrap my head around this! Safe travels!

**Comment by cswank** [comment]
Thanks!

**Review by dusk125 — APPROVED** [review]

**Pull request merged**
