### PR TITLE
Pcm

### PR DESCRIPTION
**Pull request by crazybber**
merge pcm

### CODE REVIEW

**Comment by makeworld-the-better-one** [comment]
This looks identical to #105 which @icholy closed, saying it wasn't ready. What makes yours different?

**Comment by ashutoshgngwr** [comment]
Output of `ffmpeg -formats | grep -i "pcm`.
```

DE alaw            PCM A-law
DE f32be           PCM 32-bit floating-point big-endian
DE f32le           PCM 32-bit floating-point little-endian
DE f64be           PCM 64-bit floating-point big-endian
DE f64le           PCM 64-bit floating-point little-endian
DE mulaw           PCM mu-law
DE s16be           PCM signed 16-bit big-endian
DE s16le           PCM signed 16-bit little-endian
DE s24be           PCM signed 24-bit big-endian
DE s24le           PCM signed 24-bit little-endian
DE s32be           PCM signed 32-bit big-endian
DE s32le           PCM signed 32-bit little-endian
DE s8              PCM signed 8-bit
D  sln             Asterisk raw pcm
DE u16be           PCM unsigned 16-bit big-endian
DE u16le           PCM unsigned 16-bit little-endian
DE u24be           PCM unsigned 24-bit big-endian
DE u24le           PCM unsigned 24-bit little-endian
DE u32be           PCM unsigned 32-bit big-endian
DE u32le           PCM unsigned 32-bit little-endian
DE u8              PCM unsigned 8-bit
DE vidc            PCM Archimedes VIDC
```

This implementation only understands `s16le` raw PCM. Package name `pcm` is misguiding in that sense.

**Comment by dusk125** [comment]
> 
> 
> This looks identical to #105 which @icholy closed, saying it wasn't ready. What makes yours different?

@crazybber Can you comment on this please?

**Comment by ashutoshgngwr** [comment]
@dusk125 These are the same commits from the original PR (#105), and thus incomplete.

**Comment by dusk125** [comment]
Sorry, definitely missed that these are just the same commits, I thought crazybber had implemented/reimplemented it. 
Given that this is the same and icholy said they would reopen when it was ready, I'm going to close this PR. @crazybber, if you have changes you would like to contribute to this issue, please feel free to reopen this PR with your additional changes.

**Comment by icholy** [comment]
I ended up rewriting that PCM handling code specifically for a live streaming scenario I had. I was hoping that I could create a general purpose version that would also work for my use case. Now I'm not sure if that's actually possible. I'd be more inclined to add some example code showing how to use encode/decode PCM rather than including actual encoder/decoder implementations.

**Pull request closed without merging**
